name: App build
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install mops
        uses: caffeinelabs/setup-mops@v1

      - name: Install toolchain
        run: mops install

      - name: Show moc version
        run: mops toolchain bin moc || mops toolchain use moc latest

      - name: Show mops version
        run: |
          mops --version
          $(mops toolchain bin moc) --version

      - name: Show pocket-ic version
        run: mops toolchain bin pocket-ic

      - name: Run example benchmarks
        run: mops bench
